// sw.js — GorkhaTV service worker
// Cache-first for static app shell assets; everything else (the /api/*
// backend, YouTube embeds, dynamic SSR pages) goes straight to network.

const CACHE_NAME = "gorkhatv-shell-20260904T163941Z";

// Every local JS/CSS file is listed here (not just the ones directly
// <script>/<link>-tagged in HTML) — most are only ever reached via a
// relative ES module import (e.g. home.js's `import ... from './api.js'`),
// and a relative import never carries a query-string cache-buster from its
// parent, so a "?v=" trick on the top-level <script> tag alone would miss
// every transitively-imported module (api.js, auth.js, admin-common.js,
// ...). Listing them all here instead means the SW's install-time refetch
// (below) refreshes every one of them on every deploy, uniformly, with no
// per-file bookkeeping — the js/css entries in this array are generated by
// scripts/bump-sw-cache.mjs from gorkhatv2/js/*.js and gorkhatv2/css/*.css
// on every `npm run deploy`; edit the static entries above the markers by
// hand, never the generated block itself.
const SHELL_ASSETS = [
  "/",
  "/logo-circle.png",
  "/logo-horizantal.png",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/manifest.json",
  // AUTO-GENERATED-ASSETS-START
  "/css/admin.css",
  "/css/style.css",
  "/js/admin-analytics.js",
  "/js/admin-chart.js",
  "/js/admin-common.js",
  "/js/api.js",
  "/js/auth.js",
  "/js/browse.js",
  "/js/comments.js",
  "/js/commentsDrawer.js",
  "/js/creator.js",
  "/js/edit-profile.js",
  "/js/feed.js",
  "/js/home.js",
  "/js/mobileNav.js",
  "/js/my-favourites.js",
  "/js/search.js",
  "/js/shorts.js",
  "/js/submit-channel.js",
  "/js/watch.js",
  "/js/youtubeApi.js",
  // AUTO-GENERATED-ASSETS-END
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      // Add individually so one missing file doesn't fail the whole install.
      // Plain cache.add(url) is subject to the browser's ordinary HTTP cache
      // for that request — if a stale copy of e.g. js/home.js was already
      // cached from an earlier visit (Cache-Control: max-age=14400 on static
      // assets), cache.add() can silently reuse it, poisoning this BRAND NEW
      // versioned cache with old content even though CACHE_NAME itself is
      // new (confirmed directly: a fresh cache generation held a stale
      // js/home.js after rapid same-session redeploys). fetch(url, {cache:
      // 'reload'}) forces a real network round-trip, bypassing HTTP cache,
      // so every new SW version's shell is guaranteed fresh.
      return Promise.all(
        SHELL_ASSETS.map((url) =>
          fetch(url, { cache: "reload" })
            .then((response) => cache.put(url, response))
            .catch((err) => console.warn("[sw] skip", url, err))
        )
      );
    })
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle GET requests on our own origin
  if (request.method !== "GET" || url.origin !== self.location.origin) {
    return;
  }

  // Never cache the API, or anything with a query string (dynamic pages)
  if (url.pathname.startsWith("/api/") || url.search) {
    return;
  }

  // Cache-first for shell assets, fall back to network
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;

      return fetch(request)
        .then((response) => {
          // Cache successful same-origin static responses for next time
          if (response.ok && SHELL_ASSETS.includes(url.pathname)) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
          }
          return response;
        })
        .catch(() => {
          // Offline fallback: serve cached homepage for navigation requests
          if (request.mode === "navigate") {
            return caches.match("/");
          }
        });
    })
  );
});
